name: Build and Test 

on:
  pull_request:
    branches: 
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
            
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: install
      run: yarn install

    - name: build
      run: yarn build
      
  test:
    runs-on: ubuntu-latest
    if: github.actor!= 'dependabot[bot]'
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
            
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
        
    - name: Publish Project to Chromatic
      uses: chromaui/action@v1
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
